# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
